language: cpp
addons:
  apt:
    sources: 
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - g++-9
      - libclang-common-9-dev
      - libboost-all-dev
      - libssl-dev
      - cmake
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script: cmake CMakeLists.txt && make
