language: cpp
addons:
  apt:
    sources: 
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - g++-9
      - clang++-9
      - clang++-7
      - libboost-all-dev
      - libssl-dev
      - cmake
compiler: clang
  env:
    - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

compiler: gcc
  env:
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

script: cmake CMakeLists.txt && make
