language: cpp
compiler:
  - clang++
  - gcc
env: BUILD=Debug STANDARD=17 cxxflags="-DBOOST_TRAVISCI_BUILD"
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev
addons:
  apt:
    sources: 
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - g++-9
      - libboost-all-dev
      - libssl-dev
      - cmake

script: cmake CMakeLists.txt && make
