//
// Created by prise on 10/24/21.
//

#ifndef OPENTORRENT_OPENTORRENT_LIBPEERWIRE_PROTOCOL_WIRE_H_
#define OPENTORRENT_OPENTORRENT_LIBPEERWIRE_PROTOCOL_WIRE_H_

class Wire {};

#endif  // OPENTORRENT_OPENTORRENT_LIBPEERWIRE_PROTOCOL_WIRE_H_
